version: '3.8'

services:
  sftp-server:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      args:
        - SFTP_PASSWORD=testpassword  # Can be overridden with environment variable
    # Container name for easier reference
    container_name: sftp_log_server
    # Port mapping: Map host port 2222 to container port 22
    ports:
      - "2222:22"
    # Enable health checking
    healthcheck:
      test: ["CMD", "pgrep", "sshd"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Mount volumes for persistent logs (optional)
    volumes:
      - ./sample_logs_generated:/home/sftpuser/logs
    # Restart policy
    restart: unless-stopped
    # Environment variables (optional, for demonstration)
    environment:
      - TZ=UTC